# Generated by Django 4.0.2 on 2022-02-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=30)),
                ('tmarital_status', models.CharField(max_length=10)),
                ('tdate_in', models.DateTimeField()),
                ('troom_type', models.CharField(choices=[('2 Br', 'Two bedroom'), ('3 Br', 'Three bedroom'), ('1 Br', 'One bedroom'), ('Bst', 'Bedsitter')], max_length=300)),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'Todo',
            },
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
