# Generated by Django 4.0.2 on 2022-02-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_tenants_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='tdate_in',
            field=models.DateField(),
        ),
    ]
