# Generated by Django 4.0.2 on 2022-02-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0003_alter_tenants_tdate_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenants',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='tdate_in',
        ),
        migrations.AddField(
            model_name='tenants',
            name='tyear_in',
            field=models.IntegerField(default=2021),
        ),
    ]
