# Generated by Django 4.0.2 on 2022-02-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0004_alter_tenants_options_remove_tenants_tdate_in_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenants',
            new_name='Tenant',
        ),
    ]
